public enum EtcEffectInfo : int
{
    EEP_NONE = 0,
    EEP_FIRECRACKERSMALL = 1,
    EEP_FIRECRACKERMIDDLE = 2,
    EEP_FIRECRACKERLARGE = 3,
    EEP_GRADENONE = 4,
    EEP_GRADED = 5,
    EEP_GRADEC = 6,
    EEP_GRADEB = 7,
    EEP_GRADEA = 8,
    EEP_GRADES = 9
}